const dataSet = [
  'See : Northern Lights (Aurora Borealis) See : Northern Lights (Aurora Borealis)',
  'Ride : in a hot air balloon Ride : in a hot air balloon',
  'See : Grand Canyon, Arizona See : Grand Canyon, Arizona',
  'Swim: with dolphins swim: with dolphins',
  'go: on safari go: on safari',
  'Do : Sleep under the stars',
  'Ride : in a helicopter Ride : in a helicopter',
  'go: on a road trip.',
  'Travel: Italy Travel: Italy',
  'Do : Make a difference in someone\'s life',
  'Travel: to the seven continents Travel: to the seven continents',
  'See : Great Barrier Reef See : Great Barrier Reef',
  'Do : scuba diving Do : scuba diving',
  'Do : Shower in a waterfall.',
  'Do : sky diving Do : sky diving',
  'Do : Get married',
  'See : Great Wall of China See : Great Wall of China',
  'Travel: Australia Travel: Australia',
  'Ride : an elephant Ride : an elephant',
  'learn: a foreign language (or 2 or more!)',
  'go: whale-watching go: whale-watching',
  'See : 7 New Wonders of the World See : 7 New Wonders of the World',
  'Travel: France Travel: France',
  'See : New Years Eve at Times Square (New York)',
  'Do : Raise a happy and healthy child',
];

export default dataSet;
